version: '3.9'

services:

    nginx:
        build:
            context: ..
            dockerfile: docker/nginx/Dockerfile
        restart: unless-stopped
        working_dir: /application
        volumes:
            - ../:/application
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks:
            - backend
    mysql:
        image: bitnami/mariadb:latest
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root123
            MYSQL_DATABASE: laravel2

        ports:
            - 3306:3306

        networks:
            - backend
    php-fpm:
        build:
            context: ..
            dockerfile: docker/php-fpm/Dockerfile
        restart: unless-stopped
        container_name: php2
        environment:
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
        volumes:
            - ../:/application
            - ./php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
            - ./php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./php-fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./php-fpm/logs/xdebug.log:/var/logs/xdebug/xdebug.log
        networks:
            - backend
networks:
    backend:
        name: gdocks
        driver: bridge

