version: '3.9'

services:

    nginx:
        platform: linux/amd64
        build:
            context: ..
            dockerfile: docker/nginx/Dockerfile
        restart: unless-stopped
        working_dir: /application
        volumes:
            - ../:/application
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks:
            - backend


    php-fpm:
        platform: linux/amd64
        build:
            context: ..
            dockerfile: docker/php-fpm/Dockerfile
        restart: unless-stopped
        container_name: php2
        volumes:
            - ../:/application
            - ./php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
            - ./php-fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - backend
networks:
    backend:
        name: gdocks
        driver: bridge

